services:
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: back-end-django-tasks
    network_mode: "host"
    ports:
      - "127.0.0.1:8000:8000"

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: front-end-tasks
    network_mode: "host"
    ports:
        - "127.0.0.1:5173:5173"

    depends_on:
      - backend
